Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - sandbox
    - production
    - testing
    - demo
