Style/ArgumentsForwarding:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/*.rb

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  EnforcedShorthandSyntax: never
  Exclude:
    - config/routes.rb

Style/Lambda:
  Enabled: false

Style/MapToHash:
  Enabled: false

Style/NumberedParametersLimit:
  Max: 2

Style/RedundantLineContinuation:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false
